---
title: |
       | POLI SCI 490
       | R Workshop
       | 2024-2025
format: 
  typst:
    margin:
      x: 1in
      y: 1in
fontsize: 12pt
---

```{=typst} 
#show link: set text(blue)
```

<!-- Remember double space for line skip -->
**Organizer:** Gustavo Diaz  
**Email:** <gustavo.diaz@northwestern.edu>  
**Time and Place:**  Mondays TBD.   
Fill your availability for Fall 2024 here: <https://www.when2meet.com/?26570251-3LYiF>    
**GitHub Repository:** <https://github.com/gustavo-diaz/r-workshop>  
**Office Hours:** <https://calendly.com/gustavo-diaz-nu/f24-meetings> 


# Overview

The R Workshop is a year-long series that meets three times per quarter during the academic year. The purpose of the workshop is to learn, practice, and update cutting edge statistical programming skills as they apply to quantitative and computational social science.

Most workshop meetings will feature an introduction to a new tool/method/approach and practice. Once per term, usually toward the end of the quarter, we will have an open-ended coding session in which you can work on any project that may benefit from the group setting, or we can use that time to collective learn something new (e.g. incorporating generative AI into our coding workflow).

The workshop is open to everyone, but those formally enrolled will receive full credits by attending to every meeting. We will meet on TBD (unsure if there will be a pre-determined time or if we can arrange it on our own).

The aim is to present topics that are equally useful for new and advanced users. So if you see a topic that you are already confident on, chances are that you will still learn something new. The open-ended coding sessions are also a good instance to learn some intangible skills.

# Schedule

## Fall

### Meeting 1: Writing papers in Quarto

### Meeting 2: Presentations and posters

### Meeting 3: Coding session

&nbsp;

## Winter

### Meeting 4: Figures and data visualization
<!-- Gina Reynolds -->

### Meeting 5: Descriptive tables and model summaries
<!-- Vincent Arel-Bundock, Andrew Heiss -->

### Meeting 6: Coding session

&nbsp;

## Spring

### Meeting 7: Text and images as data
<!-- Nora Webb-Williams is close! -->


### Meeting 8: Declaring and diagnosing research designs
<!-- Graeme Blair, Alex Coppock, Macartan Humphreys -->


### Meeting 9: Coding session

# Details Subject to Change

Please note that the specifics of this workshop are subject to change in the case of unforeseen circumstances.